# Generated by Django 5.1.3 on 2025-05-14 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateTimeField(auto_now_add=True)),
                ('execution_time_ms', models.FloatField()),
                ('transactions_evaluated', models.IntegerField()),
                ('alerts_generated', models.IntegerField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='transaction_monitoring.amlrules')),
            ],
            options={
                'db_table': 'rule_executions',
                'ordering': ['-execution_date'],
            },
        ),
        migrations.CreateModel(
            name='TransactionTypeGroup',
            fields=[
                ('group_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='transaction_monitoring.transactiontypegroup')),
            ],
            options={
                'db_table': 'transaction_type_groups',
                'ordering': ['group_code'],
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('transaction_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('jurisdiction', models.CharField(blank=True, max_length=3, null=True)),
                ('groups', models.ManyToManyField(related_name='transaction_types', to='transaction_monitoring.transactiontypegroup')),
            ],
            options={
                'db_table': 'transaction_types',
                'ordering': ['transaction_code'],
            },
        ),
        migrations.CreateModel(
            name='ScoringThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_type', models.CharField(choices=[('ACTIVITY_VALUE', 'Activity Value'), ('RECURRENCE', 'Recurrence'), ('COUNTRY_RISK', 'Country Risk'), ('PARTY_RISK', 'Party Risk'), ('ACCOUNT_AGE', 'Account Age')], max_length=50)),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('score', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_thresholds', to='transaction_monitoring.amlrules')),
            ],
            options={
                'db_table': 'scoring_thresholds',
                'ordering': ['rule', 'factor_type', 'threshold_value'],
                'unique_together': {('rule', 'factor_type', 'threshold_value')},
            },
        ),
    ]
