# Generated by Django 5.1.3 on 2025-05-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_monitoring', '0002_ruleexecution_transactiontypegroup_transactiontype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amlrules',
            name='min_alert_score',
            field=models.IntegerField(default=50),
        ),
    ]
