# Generated by Django 5.1.3 on 2025-05-14 14:26

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_monitoring', '0003_amlrules_min_alert_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='amlrules',
            name='custom_parameters',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='alert_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='scoring_algorithm',
            field=models.CharField(choices=[('MAX', 'Maximum Factor Score'), ('AVG', 'Average of Factor Scores'), ('SUM', 'Sum of Factor Scores'), ('WEIGHTED', 'Weighted Factors')], default='MAX', max_length=20),
        ),
    ]
