# Generated by Django 5.1.3 on 2025-05-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_monitoring', '0004_amlrules_custom_parameters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringthreshold',
            name='lookback_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='currency_exchange_count_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='currency_exchange_time_window',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='dormant_account_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='dormant_activity_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='dormant_days_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='frequent_currency_exchange',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='high_risk_countries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='high_risk_jurisdictions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='high_risk_jurisdictions_customers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='inconsistent_amount_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='inconsistent_transactions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='large_cash_deposits',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='large_cash_deposits_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='large_payments',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='large_payments_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='large_transfers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='large_transfers_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='large_withdrawals',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='large_withdrawals_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='nonprofit_suspicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='nonprofit_transaction_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='rapid_fund_movement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='rapid_movement_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='rapid_movement_window',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='shell_companies',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='shell_company_age_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='small_frequent_transfers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='small_transfer_frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='small_transfer_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='small_transfer_window',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='structured_deposits',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='structured_deposits_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='structured_deposits_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='structured_deposits_window',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
