# Generated by Django 5.1.3 on 2025-05-15 09:39

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_monitoring', '0005_scoringthreshold_lookback_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleType',
            fields=[
                ('type_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rule_types',
                'ordering': ['type_id'],
            },
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='currency_exchange_count_threshold',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='currency_exchange_time_window',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='dormant_activity_amount',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='dormant_days_threshold',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='high_risk_countries',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='inconsistent_amount_multiplier',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='large_cash_deposits_threshold',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='large_payments_threshold',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='large_transfers_threshold',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='large_withdrawals_threshold',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='nonprofit_transaction_threshold',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='rapid_movement_percentage',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='rapid_movement_window',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='shell_company_age_threshold',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='small_transfer_frequency',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='small_transfer_threshold',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='small_transfer_window',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='structured_deposits_count',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='structured_deposits_threshold',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='structured_deposits_window',
        ),
        migrations.AlterField(
            model_name='amlrules',
            name='account_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DormantAccountConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dormancy_period_days', models.IntegerField(blank=True, null=True)),
                ('activity_amount_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dormant_account_config', to='transaction_monitoring.amlrules')),
            ],
            options={
                'db_table': 'dormant_account_configs',
            },
        ),
        migrations.CreateModel(
            name='HighRiskCountryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_codes', models.TextField(blank=True, null=True)),
                ('amount_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='high_risk_country_config', to='transaction_monitoring.amlrules')),
            ],
            options={
                'db_table': 'high_risk_country_configs',
            },
        ),
        migrations.CreateModel(
            name='LargeCashConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('aggregate_period_days', models.IntegerField(blank=True, null=True)),
                ('include_foreign_currency', models.BooleanField(default=True)),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='large_cash_config', to='transaction_monitoring.amlrules')),
            ],
            options={
                'db_table': 'large_cash_configs',
            },
        ),
        migrations.CreateModel(
            name='RecurrenceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrences_threshold', models.IntegerField(blank=True, null=True)),
                ('lookback_period_days', models.IntegerField(blank=True, null=True)),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_config', to='transaction_monitoring.amlrules')),
            ],
            options={
                'db_table': 'recurrence_configs',
            },
        ),
        migrations.CreateModel(
            name='StructuredTransactionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('transaction_count_threshold', models.IntegerField(blank=True, null=True)),
                ('time_window_days', models.IntegerField(blank=True, null=True)),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structured_transaction_config', to='transaction_monitoring.amlrules')),
            ],
            options={
                'db_table': 'structured_transaction_configs',
            },
        ),
        migrations.CreateModel(
            name='RuleTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('count_threshold', models.IntegerField(blank=True, null=True)),
                ('time_window_days', models.IntegerField(blank=True, null=True)),
                ('percentage_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lookback_period_days', models.IntegerField(blank=True, null=True)),
                ('additional_parameters', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_type_configs', to='transaction_monitoring.amlrules')),
                ('rule_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_configs', to='transaction_monitoring.ruletype')),
            ],
            options={
                'db_table': 'rule_type_configs',
                'unique_together': {('rule', 'rule_type')},
            },
        ),
    ]
