# Generated by Django 5.1.3 on 2025-05-15 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_monitoring', '0006_ruletype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormantAccountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_age_days', models.IntegerField(default=90, help_text='Minimum age of account in days to be considered for dormancy checks')),
                ('inactive_period_months', models.IntegerField(default=3, help_text='Number of months with minimal activity to consider account dormant')),
                ('activity_amount_threshold', models.DecimalField(decimal_places=2, default=5000.0, help_text='Minimum amount to trigger alert when activity occurs in dormant account', max_digits=20)),
                ('max_prior_activity', models.DecimalField(decimal_places=2, default=1000.0, help_text='Maximum allowed activity amount during dormancy period', max_digits=20)),
            ],
            options={
                'db_table': 'dormant_account_rules',
            },
        ),
        migrations.CreateModel(
            name='LargeCashRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_amount', models.DecimalField(decimal_places=2, default=10000.0, help_text='Threshold amount to trigger the rule', max_digits=20)),
                ('aggregate_period_days', models.IntegerField(default=30, help_text='Period in days over which to aggregate transactions')),
                ('include_foreign_currency', models.BooleanField(default=True, help_text='Whether to include foreign currency transactions in the detection')),
                ('monitor_deposits', models.BooleanField(default=True, help_text='Monitor cash deposits')),
                ('monitor_withdrawals', models.BooleanField(default=True, help_text='Monitor cash withdrawals')),
            ],
            options={
                'db_table': 'large_cash_rules',
            },
        ),
        migrations.RemoveField(
            model_name='dormantaccountconfig',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='largecashconfig',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='dormant_account_activity',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='frequent_currency_exchange',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='high_risk_jurisdictions',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='high_risk_jurisdictions_customers',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='inconsistent_transactions',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='large_cash_deposits',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='large_payments',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='large_transfers',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='large_withdrawals',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='nonprofit_suspicious',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='rapid_fund_movement',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='recurrence_settings',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='shell_companies',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='small_frequent_transfers',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='structured_deposits',
        ),
        migrations.RemoveField(
            model_name='amlrules',
            name='thresholds',
        ),
        migrations.AddField(
            model_name='amlrules',
            name='rule_type',
            field=models.CharField(blank=True, choices=[('DORMANT_ACCOUNT', 'Dormant Account Activity'), ('LARGE_CASH', 'Large Cash Transactions')], max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='amlrules',
            index=models.Index(fields=['rule_type'], name='aml_rules_rule_ty_89fed9_idx'),
        ),
        migrations.AddField(
            model_name='dormantaccountrule',
            name='rule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dormant_account_config', to='transaction_monitoring.amlrules'),
        ),
        migrations.AddField(
            model_name='largecashrule',
            name='rule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='large_cash_config', to='transaction_monitoring.amlrules'),
        ),
        migrations.DeleteModel(
            name='DormantAccountConfig',
        ),
        migrations.DeleteModel(
            name='LargeCashConfig',
        ),
    ]
