# Generated by Django 5.1.3 on 2025-03-13 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField()),
                ('date_blacklisted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('id_document_type', models.CharField(blank=True, choices=[('Passport', 'Passport'), ('National ID', 'National ID'), ('Driver License', 'Driver License'), ('Other', 'Other')], max_length=50, null=True)),
                ('id_document_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuspiciousTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('flagged_reason', models.TextField()),
                ('manual_review_required', models.BooleanField(default=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('sender_account', models.CharField(max_length=50)),
                ('receiver_account', models.CharField(max_length=50)),
                ('customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_currency', models.CharField(max_length=10)),
                ('received_currency', models.CharField(max_length=10)),
                ('sender_bank_location', models.CharField(max_length=100)),
                ('receiver_bank_location', models.CharField(max_length=100)),
                ('payment_type', models.CharField(choices=[('Wire Transfer', 'Wire Transfer'), ('Cash Deposit', 'Cash Deposit'), ('Online Payment', 'Online Payment'), ('Other', 'Other')], max_length=50)),
                ('old_balance_sender', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('new_balance_sender', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('old_balance_receiver', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('new_balance_receiver', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('transaction_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Flagged', 'Flagged')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WatchlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SARReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=100, unique=True)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('report_file', models.FileField(upload_to='sar_reports/')),
                ('transactions', models.ManyToManyField(to='aml_app.suspicioustransaction')),
            ],
        ),
        migrations.AddField(
            model_name='suspicioustransaction',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aml_app.transaction'),
        ),
    ]
