# Generated by Django 5.1.3 on 2025-03-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspicioustransaction',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction',
            name='account_status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Blacklisted', 'Blacklisted')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Savings', 'Savings'), ('Current', 'Current'), ('Business', 'Business'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=-1212, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suspicioustransaction',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction',
            name='id_document_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction',
            name='id_document_type',
            field=models.CharField(blank=True, choices=[('Passport', 'Passport'), ('National ID', 'National ID'), ('Driver License', 'Driver License'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction',
            name='receiver_account',
            field=models.CharField(default=-1212, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suspicioustransaction',
            name='sender_account',
            field=models.CharField(default=-1212, max_length=50),
            preserve_default=False,
        ),
    ]
