# Generated by Django 5.1.3 on 2025-03-19 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0004_amlsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('id_document_type', models.CharField(choices=[('Passport', 'Passport'), ('National ID', 'National ID'), ('Driver License', 'Driver License'), ('Other', 'Other')], max_length=50)),
                ('id_document_number', models.CharField(max_length=100, unique=True)),
                ('id_issued_country', models.CharField(max_length=100)),
                ('id_expiry_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=150, null=True)),
                ('employer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('source_of_funds', models.CharField(blank=True, choices=[('Salary', 'Salary'), ('Business Income', 'Business Income'), ('Investments', 'Investments'), ('Inheritance', 'Inheritance'), ('Other', 'Other')], max_length=100, null=True)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('account_type', models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current'), ('Business', 'Business'), ('Other', 'Other')], max_length=50)),
                ('account_status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Closed', 'Closed'), ('Blacklisted', 'Blacklisted')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KYCTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10)),
                ('politically_exposed_person', models.BooleanField(default=False)),
                ('sanctions_list_check', models.BooleanField(default=False)),
                ('watchlist_check', models.BooleanField(default=False)),
                ('adverse_media_check', models.BooleanField(default=False)),
                ('suspicious_activity_flag', models.BooleanField(default=False)),
                ('financial_crime_check', models.BooleanField(default=False)),
                ('fraud_check', models.BooleanField(default=False)),
                ('kyc_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('reviewer', models.CharField(blank=True, max_length=255, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('audit_trail', models.TextField(blank=True, null=True)),
                ('enhanced_due_diligence_required', models.BooleanField(default=False)),
                ('transaction_monitoring_required', models.BooleanField(default=False)),
                ('high_risk_country', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kyc_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_tests', to='aml_app.kycprofile')),
            ],
        ),
    ]
