# Generated by Django 5.1.3 on 2025-03-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0005_kycprofile_kyctestresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdverseMediaCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('id_document_number', models.CharField(max_length=100, unique=True)),
                ('id_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('media_source', models.CharField(max_length=255)),
                ('headline', models.CharField(max_length=500)),
                ('article_url', models.URLField(blank=True, null=True)),
                ('date_published', models.DateField()),
                ('risk_assessment', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('category', models.CharField(choices=[('Fraud', 'Fraud'), ('Money Laundering', 'Money Laundering'), ('Terrorism Financing', 'Terrorism Financing'), ('Corruption', 'Corruption'), ('Other', 'Other')], max_length=100)),
                ('flagged_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SanctionsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('id_document_number', models.CharField(max_length=100, unique=True)),
                ('id_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('sanctions_source', models.CharField(choices=[('OFAC', 'OFAC'), ('UN', 'UN'), ('EU', 'EU'), ('FATF', 'FATF'), ('Other', 'Other')], max_length=100)),
                ('reason', models.TextField()),
                ('risk_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='High', max_length=10)),
                ('sanction_start_date', models.DateField(blank=True, null=True)),
                ('sanction_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Removed', 'Removed')], default='Active', max_length=50)),
                ('date_blacklisted', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='blacklistentry',
            name='id_document_number',
            field=models.CharField(default=-1212, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlistentry',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='watchlistentry',
            name='date_flagged',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchlistentry',
            name='id_document_number',
            field=models.CharField(default=-1212, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlistentry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchlistentry',
            name='risk_level',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='watchlistentry',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Cleared', 'Cleared')], default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='watchlistentry',
            name='watchlist_type',
            field=models.CharField(choices=[('Bank Internal', 'Bank Internal'), ('Law Enforcement', 'Law Enforcement'), ('Regulatory', 'Regulatory'), ('Third Party Data', 'Third Party Data'), ('Other', 'Other')], default=-1212, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blacklistentry',
            name='date_blacklisted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watchlistentry',
            name='added_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
