# Generated by Django 5.1.3 on 2025-03-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0006_adversemediacheck_sanctionslist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyctestresult',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kyctestresult',
            name='full_name',
            field=models.CharField(default=-1212, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyctestresult',
            name='id_document_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
