# Generated by Django 5.1.3 on 2025-03-20 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0007_kyctestresult_customer_id_kyctestresult_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticallyExposedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('id_document_number', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=255)),
                ('pep_category', models.CharField(choices=[('Government Official', 'Government Official'), ('Military', 'Military'), ('Judiciary', 'Judiciary'), ('Business Leader', 'Business Leader'), ('Other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Former', 'Former')], default='Active', max_length=20)),
                ('relationship_to_power', models.CharField(choices=[('Self', 'Self'), ('Family Member', 'Family Member'), ('Close Associate', 'Close Associate')], max_length=100)),
                ('risk_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='High', max_length=10)),
                ('date_listed', models.DateField()),
                ('date_removed', models.DateField(blank=True, null=True)),
                ('reason_flagged', models.TextField()),
                ('enhanced_due_diligence_required', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('kyc_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pep_status', to='aml_app.kycprofile')),
            ],
        ),
    ]
