# Generated by Django 5.1.3 on 2025-03-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0008_politicallyexposedperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycprofile',
            name='id_document_file',
            field=models.FileField(blank=True, null=True, upload_to='id_documents/'),
        ),
    ]
