# Generated by Django 5.1.3 on 2025-03-25 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0009_kycprofile_id_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('overall_risk', models.CharField(blank=True, max_length=10)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RiskFactorAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
                ('risk_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aml_app.riskassessment')),
                ('risk_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aml_app.riskfactor')),
            ],
        ),
    ]
