# Generated by Django 5.1.3 on 2025-03-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0010_riskassessment_riskfactor_riskfactorassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, help_text='Country selected for risk assessment', max_length=100)),
                ('country_risk', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], help_text='Risk rating based on country')),
                ('source_risk', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], help_text='Risk rating based on source of funds')),
                ('overall_risk', models.CharField(blank=True, help_text='Overall risk category (Low, Medium, High)', max_length=50)),
                ('calculated_score', models.PositiveSmallIntegerField(blank=True, help_text='Total numerical score', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
