# Generated by Django 5.1.3 on 2025-03-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0011_riskscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('country', 'Country'), ('source', 'Source of Funds')], max_length=20)),
                ('value', models.CharField(help_text='Country name or Source of Funds type', max_length=100)),
                ('risk_rating', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], help_text='Risk rating (1=Low, 2=Medium, 3=High)')),
            ],
        ),
    ]
