# Generated by Django 5.1.3 on 2025-03-25 14:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0012_riskdefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskdefinition',
            name='risk_category',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='riskdefinition',
            name='risk_rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Risk rating as a percentage (0-100)', max_digits=5),
        ),
    ]
