# Generated by Django 5.1.3 on 2025-03-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0013_riskdefinition_risk_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
