# Generated by Django 5.1.3 on 2025-04-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0014_transaction_is_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='DilisenseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='Private API key for accessing the DILISense API', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'API Conf',
            },
        ),
    ]
