# Generated by Django 5.1.3 on 2025-04-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0016_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amlsettings',
            name='circular_transaction_days',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='geo_location_mismatch',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='multiple_beneficiaries',
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='circular_transaction_window',
            field=models.IntegerField(default=72, help_text='Hours within which circular transactions are flagged.'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='connection_failure_action',
            field=models.CharField(default='Default to stricter thresholds', help_text='Action to take on connection failure.', max_length=50),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='critical_alert_action',
            field=models.CharField(default='Immediate freeze and manual review', help_text='Action to take for critical alerts.', max_length=100),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='geo_location_count',
            field=models.IntegerField(default=3, help_text='Number of locations for geo-location mismatch detection.'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='geo_location_window',
            field=models.IntegerField(default=24, help_text='Time window in hours for geo-location mismatch detection.'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='high_alert_action',
            field=models.CharField(default='Transaction hold and next-day review', help_text='Action to take for high alerts.', max_length=100),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='high_cash_ratio_threshold',
            field=models.IntegerField(default=70, help_text='Percentage threshold for high cash ratio.'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='high_cash_ratio_window',
            field=models.IntegerField(default=30, help_text='Time window in days for high cash ratio calculation.'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='high_priority_alerts',
            field=models.TextField(default='Foreign transfers to high-risk countries, rapid withdrawals after deposit', help_text='Description of high priority alerts.'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='linked_account_transfer_threshold',
            field=models.IntegerField(default=2, help_text='Threshold for linked account transfers.'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='low_priority_alerts',
            field=models.TextField(default='Round figures, high cash ratio', help_text='Description of low priority alerts.'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='max_processing_latency',
            field=models.IntegerField(default=3, help_text='Maximum processing latency in seconds.'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='medium_priority_alerts',
            field=models.TextField(default='Structuring attempts, dormant account activation', help_text='Description of medium priority alerts.'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='min_frequency',
            field=models.IntegerField(default=3, help_text='Minimum frequency of transactions for electronic structuring.'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='multiple_beneficiaries_count',
            field=models.IntegerField(default=5, help_text='Number of different beneficiaries before flagging.'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='multiple_beneficiaries_days',
            field=models.IntegerField(default=7, help_text='Time window in days for multiple beneficiaries detection.'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='pep_enhanced_monitoring',
            field=models.BooleanField(default=True, help_text='Enable enhanced monitoring for Politically Exposed Persons.'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='rapid_withdrawal_threshold',
            field=models.IntegerField(default=90, help_text='Percentage threshold for rapid withdrawals.'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='rapid_withdrawal_window',
            field=models.IntegerField(default=24, help_text='Time window in hours for rapid withdrawal detection.'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='round_figures_detection',
            field=models.CharField(choices=[('Multiples of $1,000', 'Multiples of $1,000'), ('Multiples of $500', 'Multiples of $500'), ('Multiples of $100', 'Multiples of $100')], default='Multiples of $1,000', help_text='Round figure detection threshold', max_length=30),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='standard_alert_action',
            field=models.CharField(default='Flag for routine review within 48 hours', help_text='Action to take for standard alerts.', max_length=100),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='structuring_max_amount',
            field=models.FloatField(default=9999, help_text='Maximum amount per transaction for structuring detection.'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='structuring_time_window',
            field=models.IntegerField(default=48, help_text='Time window in hours for structuring detection.'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='time_window_days',
            field=models.IntegerField(default=7, help_text='Time window in days for electronic structuring detection.'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='transaction_queue_priority',
            field=models.CharField(default='High-value transactions first', help_text='Transaction queue priority setting.', max_length=50),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='transfer_time_window',
            field=models.IntegerField(default=1, help_text='Time window in hours for transfer detection.'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='watchlist_check_frequency',
            field=models.CharField(default='Real-time', help_text='Frequency of watchlist checks.', max_length=20),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='cash_deposit_limit',
            field=models.FloatField(default=5000, help_text='Maximum cash deposit amount before flagging.'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='cash_deposit_no_withdrawal',
            field=models.FloatField(default=15000, help_text='Flag high cash deposits with no withdrawals.'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='high_risk_countries',
            field=models.TextField(default='Afghanistan,North Korea,Myanmar,Iran', help_text='Comma-separated list of high-risk countries.'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='inactive_days',
            field=models.IntegerField(default=60, help_text='Days an account must be inactive before considered dormant.'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='mismatched_behavior_multiplier',
            field=models.FloatField(default=3, help_text='Multiplier for mismatched customer behavior.'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='structuring_limit',
            field=models.FloatField(default=3000, help_text='Threshold for detecting structuring transactions.'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='structuring_txn_count',
            field=models.IntegerField(default=3, help_text='Minimum count of structuring transactions before flagging.'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='transaction_threshold',
            field=models.FloatField(default=10000, help_text='Maximum transaction amount before flagging.'),
        ),
    ]
