# Generated by Django 5.1.3 on 2025-04-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0017_remove_amlsettings_circular_transaction_days_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amlsettings',
            options={'verbose_name': 'AML Configuration', 'verbose_name_plural': 'AML Configurations'},
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='cash_deposit_no_withdrawal',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='geo_location_count',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='geo_location_window',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='inactive_days',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='linked_account_transfer_threshold',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='min_frequency',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='round_figures_detection',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='structuring_limit',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='structuring_max_amount',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='structuring_time_window',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='structuring_txn_count',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='time_window_days',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='transaction_threshold',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='watchlist_check_frequency',
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='account_type',
            field=models.CharField(choices=[('individual_savings', 'Individual Savings'), ('individual_current', 'Individual Current'), ('business', 'Business Accounts'), ('trust', 'Trust Accounts'), ('wealth', 'Wealth Management')], default='individual_savings', max_length=20),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='cash_deposit_without_withdrawal',
            field=models.FloatField(default=15000),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='cash_max_amount_per_tx',
            field=models.FloatField(default=9999),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='cash_min_transaction_count',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='cash_time_window',
            field=models.IntegerField(default=48, help_text='In hours'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='electronic_min_frequency',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='electronic_round_figures',
            field=models.CharField(choices=[('1000', 'Multiples of $1,000'), ('500', 'Multiples of $500'), ('100', 'Multiples of $100')], default='1000', max_length=4),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='electronic_time_window',
            field=models.IntegerField(default=7, help_text='In days'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='geo_mismatch_hours',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='geo_mismatch_locations',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='inactive_days_threshold',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='linked_account_threshold',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='max_transaction_amount',
            field=models.FloatField(default=10000),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='structuring_detection_limit',
            field=models.FloatField(default=3000),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='watchlist_check_freq',
            field=models.CharField(choices=[('realtime', 'Real-time'), ('hourly', 'Hourly batch'), ('daily', 'Daily batch')], default='realtime', max_length=8),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='cash_deposit_limit',
            field=models.FloatField(default=5000),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='circular_transaction_window',
            field=models.IntegerField(default=72, help_text='In hours'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='connection_failure_action',
            field=models.CharField(choices=[('stricter', 'Default to stricter thresholds'), ('hold', 'Hold all transactions'), ('flag', 'Process with manual review flag')], default='stricter', max_length=10),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='critical_alert_action',
            field=models.CharField(choices=[('freeze', 'Immediate freeze and manual review'), ('block', 'Block transaction and notify compliance'), ('hold', 'Hold transaction and alert manager'), ('routine', 'Flag for routine review within 48 hours'), ('process', 'Process with notification to compliance')], default='freeze', max_length=7),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='dormant_account_transfer_limit',
            field=models.FloatField(default=5000),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='employee_risk_flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='high_alert_action',
            field=models.CharField(choices=[('freeze', 'Immediate freeze and manual review'), ('block', 'Block transaction and notify compliance'), ('hold', 'Hold transaction and alert manager'), ('routine', 'Flag for routine review within 48 hours'), ('process', 'Process with notification to compliance')], default='hold', max_length=7),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='high_cash_ratio_threshold',
            field=models.FloatField(default=70),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='high_cash_ratio_window',
            field=models.IntegerField(default=30, help_text='In days'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='high_priority_alerts',
            field=models.TextField(default='Foreign transfers to high-risk countries, rapid withdrawals after deposit'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='high_risk_countries',
            field=models.TextField(default='Afghanistan,North Korea,Myanmar,Iran', help_text='Comma-separated list'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='low_priority_alerts',
            field=models.TextField(default='Round figures, high cash ratio'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='max_processing_latency',
            field=models.IntegerField(default=3, help_text='In seconds'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='medium_priority_alerts',
            field=models.TextField(default='Structuring attempts, dormant account activation'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='mismatched_behavior_multiplier',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='multiple_beneficiaries_count',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='multiple_beneficiaries_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='pep_enhanced_monitoring',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='rapid_withdrawal_threshold',
            field=models.FloatField(default=90, help_text='Percentage'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='rapid_withdrawal_window',
            field=models.IntegerField(default=24, help_text='In hours'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='standard_alert_action',
            field=models.CharField(choices=[('freeze', 'Immediate freeze and manual review'), ('block', 'Block transaction and notify compliance'), ('hold', 'Hold transaction and alert manager'), ('routine', 'Flag for routine review within 48 hours'), ('process', 'Process with notification to compliance')], default='routine', max_length=7),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='transaction_queue_priority',
            field=models.CharField(choices=[('high_value', 'High-value transactions first'), ('chronological', 'Chronological order'), ('risk', 'Risk-based prioritization')], default='high_value', max_length=13),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='transfer_time_window',
            field=models.IntegerField(default=1, help_text='In hours'),
        ),
    ]
