# Generated by Django 5.1.3 on 2025-04-10 08:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0019_amlsettingss_amlparameterrisk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycprofile',
            name='source_of_funds',
            field=models.CharField(blank=True, choices=[('Salary-Informal', 'Salary Informal '), ('Salary-Formal', 'Salary Formal '), ('Business Income (Cooperate)', 'Business Income (Cooperate)'), ('Business Income (Small Fames)', 'Business Income (Small Fames)'), ('Pension', 'Pension'), ('Investments', 'Investments'), ('Inheritance', 'Inheritance'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Transaction1',
            fields=[
                ('transaction_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('transaction_time', models.TimeField(blank=True, null=True)),
                ('transaction_timestamp', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('currency_code', models.CharField(max_length=3)),
                ('transaction_type_code', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('PAYMENT', 'Payment'), ('REFUND', 'Refund')], max_length=10)),
                ('transaction_status_code', models.CharField(choices=[('PEND', 'Pending'), ('COMP', 'Completed'), ('FAIL', 'Failed'), ('RJCT', 'Rejected'), ('CANC', 'Cancelled')], max_length=5)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('narrative', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('purpose_code', models.CharField(blank=True, max_length=10, null=True)),
                ('reason_code', models.CharField(blank=True, max_length=10, null=True)),
                ('source_account_number', models.CharField(max_length=30)),
                ('source_account_type_code', models.CharField(blank=True, max_length=5, null=True)),
                ('source_account_holder_id', models.CharField(blank=True, max_length=20, null=True)),
                ('source_customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('source_branch_code', models.CharField(blank=True, max_length=10, null=True)),
                ('destination_account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('destination_account_type_code', models.CharField(blank=True, max_length=5, null=True)),
                ('destination_account_holder_id', models.CharField(blank=True, max_length=20, null=True)),
                ('destination_customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_branch_code', models.CharField(blank=True, max_length=10, null=True)),
                ('channel_code', models.CharField(choices=[('ATM', 'ATM'), ('OLB', 'Online Banking'), ('MOB', 'Mobile Banking'), ('BRN', 'Branch'), ('POS', 'Point of Sale')], max_length=5)),
                ('location_code', models.CharField(blank=True, max_length=10, null=True)),
                ('terminal_id', models.CharField(blank=True, max_length=20, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('geo_location', models.CharField(blank=True, max_length=100, null=True)),
                ('source_country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('source_country_name', models.CharField(blank=True, max_length=50, null=True)),
                ('destination_country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('destination_country_name', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_fee', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=20, null=True)),
                ('teller_id', models.CharField(blank=True, max_length=20, null=True)),
                ('approver_id', models.CharField(blank=True, max_length=20, null=True)),
                ('aml_alert_reason_code', models.CharField(blank=True, max_length=10, null=True)),
                ('correspondent_bank_code', models.CharField(blank=True, max_length=20, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=11, null=True)),
                ('bic_code', models.CharField(blank=True, max_length=11, null=True)),
                ('routing_number', models.CharField(blank=True, max_length=20, null=True)),
                ('beneficiary_bank_code', models.CharField(blank=True, max_length=20, null=True)),
                ('intermediary_bank_code', models.CharField(blank=True, max_length=20, null=True)),
                ('document_reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('source_of_funds_code', models.CharField(blank=True, max_length=5, null=True)),
                ('obi_information', models.TextField(blank=True, null=True)),
                ('sanction_screening_result_code', models.CharField(blank=True, choices=[('PASS', 'Passed'), ('FAIL', 'Failed'), ('MREV', 'Manual Review')], max_length=5, null=True)),
                ('wire_message_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_checked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'transactions',
                'indexes': [models.Index(fields=['transaction_date'], name='transaction_transac_0d716a_idx'), models.Index(fields=['source_account_number'], name='transaction_source__9e1c90_idx'), models.Index(fields=['destination_account_number'], name='transaction_destina_6a4a25_idx'), models.Index(fields=['source_country_code'], name='transaction_source__57613c_idx'), models.Index(fields=['destination_country_code'], name='transaction_destina_b97caa_idx'), models.Index(fields=['transaction_type_code'], name='transaction_transac_7dddce_idx'), models.Index(fields=['amount'], name='transaction_amount_8c918e_idx')],
            },
        ),
    ]
