# Generated by Django 5.1.3 on 2025-04-10 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0020_alter_kycprofile_source_of_funds_transaction1'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousActivityReport',
            fields=[
                ('report_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('report_reference_number', models.CharField(max_length=50, unique=True)),
                ('report_type', models.CharField(choices=[('STR', 'Suspicious Transaction Report'), ('CTR', 'Currency Transaction Report'), ('SAR', 'Suspicious Activity Report')], max_length=10)),
                ('report_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Review'), ('SUBMITTED', 'Submitted to Authorities'), ('CLOSED', 'Closed'), ('UNDER_INVESTIGATION', 'Under Investigation')], default='DRAFT', max_length=20)),
                ('suspicious_activity_type', models.CharField(choices=[('STRUCTURING', 'Structuring'), ('MONEY_LAUNDERING', 'Money Laundering'), ('TERRORIST_FINANCING', 'Terrorist Financing'), ('FRAUD', 'Fraud'), ('IDENTITY_THEFT', 'Identity Theft'), ('UNUSUAL_ACTIVITY', 'Unusual Account Activity'), ('TAX_EVASION', 'Tax Evasion'), ('INSIDER_TRADING', 'Insider Trading'), ('SANCTIONS_VIOLATION', 'Sanctions Violation'), ('HUMAN_TRAFFICKING', 'Human Trafficking'), ('DRUG_TRAFFICKING', 'Drug Trafficking'), ('CORRUPTION', 'Corruption/Bribery'), ('OTHER', 'Other')], max_length=30)),
                ('secondary_activity_types', models.TextField(blank=True, help_text='Comma-separated list of secondary suspicious activity types', null=True)),
                ('detection_date', models.DateTimeField(help_text='When the suspicious activity was detected')),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When the report was created')),
                ('submission_date', models.DateTimeField(blank=True, help_text='When the report was submitted to authorities', null=True)),
                ('activity_start_date', models.DateField(help_text='When the suspicious activity began')),
                ('activity_end_date', models.DateField(help_text='When the suspicious activity ended')),
                ('total_suspicious_amount', models.DecimalField(decimal_places=4, help_text='Total amount involved in suspicious activity', max_digits=19)),
                ('currency_code', models.CharField(help_text='Currency of suspicious amount', max_length=3)),
                ('related_transactions', models.TextField(help_text='Comma-separated list of transaction IDs involved')),
                ('primary_subject_name', models.CharField(help_text='Name of primary subject', max_length=100)),
                ('primary_subject_id', models.CharField(help_text='Customer ID or identification number', max_length=50)),
                ('primary_subject_id_type', models.CharField(help_text='Type of ID (passport, national ID, etc.)', max_length=20)),
                ('primary_subject_address', models.TextField(help_text='Address of primary subject')),
                ('primary_subject_dob', models.DateField(blank=True, help_text='Date of birth if individual', null=True)),
                ('primary_subject_nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_subject_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_subjects', models.TextField(blank=True, help_text='JSON format of additional subjects involved', null=True)),
                ('primary_account_number', models.CharField(help_text='Primary account involved', max_length=30)),
                ('additional_accounts', models.TextField(blank=True, help_text='Comma-separated list of additional accounts involved', null=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], help_text='Risk assessment level of the suspicious activity', max_length=10)),
                ('suspicious_activity_description', models.TextField(help_text='Detailed narrative of suspicious activity')),
                ('red_flags_identified', models.TextField(help_text='Description of red flags that triggered detection')),
                ('unusual_behavior_patterns', models.TextField(blank=True, help_text='Patterns of behavior that deviated from normal', null=True)),
                ('supporting_evidence', models.TextField(blank=True, help_text='Description of evidence supporting suspicion', null=True)),
                ('internal_actions_taken', models.TextField(help_text='Actions taken by the financial institution')),
                ('account_action', models.CharField(blank=True, help_text='Action taken on accounts (e.g., frozen, closed)', max_length=50, null=True)),
                ('relationship_action', models.CharField(blank=True, help_text='Action taken on customer relationship', max_length=50, null=True)),
                ('law_enforcement_agency', models.CharField(blank=True, help_text='Agency report was submitted to', max_length=100, null=True)),
                ('law_enforcement_contact', models.CharField(blank=True, help_text='Contact person at law enforcement', max_length=100, null=True)),
                ('case_reference_number', models.CharField(blank=True, help_text='Law enforcement case reference', max_length=50, null=True)),
                ('filing_institution_name', models.CharField(help_text='Name of filing institution', max_length=100)),
                ('filing_institution_id', models.CharField(help_text='ID/License of filing institution', max_length=50)),
                ('preparer_name', models.CharField(help_text='Name of report preparer', max_length=100)),
                ('preparer_position', models.CharField(help_text='Position of report preparer', max_length=50)),
                ('preparer_contact', models.CharField(help_text='Contact info of report preparer', max_length=100)),
                ('approver_name', models.CharField(help_text='Name of report approver (e.g., MLRO)', max_length=100)),
                ('approver_position', models.CharField(help_text='Position of report approver', max_length=50)),
                ('supporting_documents', models.TextField(blank=True, help_text='List of attached supporting documents', null=True)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'suspicious_activity_reports',
            },
        ),
        migrations.CreateModel(
            name='TransactionMonitoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_transaction_threshold', models.DecimalField(decimal_places=4, default=5000.0, help_text='Threshold for cash transaction reporting (CTR)', max_digits=19)),
                ('large_cash_deposit_multiplier', models.DecimalField(decimal_places=2, default=3.0, help_text='Multiplier of customer average to flag large cash deposits', max_digits=5)),
                ('cash_structuring_threshold', models.DecimalField(decimal_places=4, default=4000.0, help_text='Threshold per transaction for structuring detection', max_digits=19)),
                ('cash_structuring_count', models.IntegerField(default=3, help_text='Number of cash transactions to trigger structuring alert')),
                ('cash_structuring_time_window_hours', models.IntegerField(default=24, help_text='Time window (hours) for cash structuring detection')),
                ('cash_exchange_frequency_threshold', models.IntegerField(default=3, help_text='Number of currency exchanges to flag in period')),
                ('cash_exchange_time_window_days', models.IntegerField(default=7, help_text='Time window (days) for currency exchange monitoring')),
                ('wire_transfer_threshold', models.DecimalField(decimal_places=4, default=3000.0, help_text='Threshold for international wire monitoring', max_digits=19)),
                ('high_risk_wire_threshold', models.DecimalField(decimal_places=4, default=1000.0, help_text='Lower threshold for wires to/from high-risk jurisdictions', max_digits=19)),
                ('high_risk_countries', models.TextField(default='MM,ID,NR,NG,PH,KP,IR,CK', help_text='Comma-separated ISO codes for high-risk jurisdictions')),
                ('rapid_movement_percentage', models.DecimalField(decimal_places=2, default=80.0, help_text='Percentage of deposit moved rapidly', max_digits=5)),
                ('rapid_movement_hours', models.IntegerField(default=48, help_text='Time window (hours) for rapid fund movement')),
                ('dormant_account_days', models.IntegerField(default=90, help_text='Days of inactivity to consider account dormant')),
                ('dormant_activity_threshold', models.DecimalField(decimal_places=4, default=3000.0, help_text='Threshold for flagging activity in dormant accounts', max_digits=19)),
                ('round_amount_detection', models.BooleanField(default=True, help_text='Enable detection of round amount transactions')),
                ('round_amount_threshold', models.DecimalField(decimal_places=4, default=1000.0, help_text='Threshold to flag round number transactions', max_digits=19)),
                ('circular_transaction_detection', models.BooleanField(default=True, help_text='Detect funds returning to originator')),
                ('circular_transaction_window_hours', models.IntegerField(default=72, help_text='Time window (hours) for circular transactions')),
                ('circular_transaction_percent_threshold', models.DecimalField(decimal_places=2, default=80.0, help_text='Percentage of amount returning to trigger alert', max_digits=5)),
                ('denomination_exchange_threshold', models.DecimalField(decimal_places=4, default=3000.0, help_text='Threshold for low-to-high denomination exchanges', max_digits=19)),
                ('multiple_account_transfer_count', models.IntegerField(default=3, help_text='Number of accounts involved to flag transfers')),
                ('missing_wire_info_action', models.CharField(choices=[('BLOCK', 'Block Transaction'), ('FLAG', 'Flag for Review'), ('ALLOW', 'Allow with Note')], default='FLAG', help_text='Action for incomplete wire info', max_length=10)),
                ('nonprofit_transaction_threshold', models.DecimalField(decimal_places=4, default=3000.0, help_text='Threshold for nonprofit transactions', max_digits=19)),
                ('shell_company_transaction_threshold', models.DecimalField(decimal_places=4, default=3000.0, help_text='Threshold for shell company transactions', max_digits=19)),
                ('pep_transaction_threshold', models.DecimalField(decimal_places=4, default=1000.0, help_text='Threshold for PEP transaction monitoring', max_digits=19)),
                ('immediate_alert_threshold', models.DecimalField(decimal_places=4, default=10000.0, help_text='Amount threshold for real-time alerts', max_digits=19)),
                ('suspicious_activity_report_threshold', models.DecimalField(decimal_places=4, default=5000.0, help_text='Threshold for SAR recommendations', max_digits=19)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transaction Monitoring Configuration',
                'verbose_name_plural': 'Transaction Monitoring Configurations',
            },
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='id_number',
            new_name='company_registration_number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id_document_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id_document_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='additional_nationalities',
            field=models.TextField(blank=True, help_text='Comma-separated list of additional nationalities', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='annual_turnover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='beneficial_owners',
            field=models.TextField(blank=True, help_text='JSON format of beneficial owners with 25%+ ownership', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='branch_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='citizenship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.CharField(default=-1212, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_segment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed'), ('DECEASED', 'Deceased'), ('WATCH', 'Watch List')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ENTITY', 'Entity/Organization')], default=-1212, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_incorporation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='edd_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='employee_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='employer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='employment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='enhanced_due_diligence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='entity_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='expected_countries',
            field=models.TextField(blank=True, help_text='Expected countries for transactions', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='expected_transaction_types',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='expected_transaction_volumes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='income_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='industry_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='industry_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_sanctioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='kyc_last_verified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='kyc_next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='kyc_status',
            field=models.CharField(choices=[('VERIFIED', 'Fully Verified'), ('PARTIAL', 'Partially Verified'), ('PENDING', 'Verification Pending'), ('FAILED', 'Verification Failed'), ('EXPIRED', 'Verification Expired')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='mailing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='modified_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='negative_media',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='negative_media_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='onboarding_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ownership_structure',
            field=models.TextField(blank=True, help_text='Description of ownership structure', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pep_associated_entity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pep_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pep_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pep_position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pep_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pep_status',
            field=models.CharField(choices=[('NOT_PEP', 'Not a PEP'), ('DIRECT_PEP', 'Direct PEP'), ('RELATIVE_PEP', 'PEP Relative'), ('ASSOCIATE_PEP', 'PEP Associate'), ('FORMER_PEP', 'Former PEP')], default='NOT_PEP', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_id_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_id_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_id_issuing_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_id_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='relationship_manager_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='residential_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='residential_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='residential_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='residential_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='residential_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='risk_factors',
            field=models.TextField(blank=True, help_text='Factors contributing to risk score', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='risk_last_assessment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='risk_next_assessment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='risk_rating',
            field=models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='risk_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sanction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sanction_list_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sanction_list_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='secondary_id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='secondary_id_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_residence_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_status'], name='customers_custome_d2fdf0_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name', 'first_name'], name='customers_last_na_89bb5f_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['entity_name'], name='customers_entity__4780c9_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['primary_id_number'], name='customers_primary_ac8429_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['risk_rating'], name='customers_risk_ra_f5cdac_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['pep_status'], name='customers_pep_sta_3a3f2a_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_sanctioned'], name='customers_is_sanc_9c0b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['kyc_status'], name='customers_kyc_sta_38146a_idx'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
        migrations.AddIndex(
            model_name='suspiciousactivityreport',
            index=models.Index(fields=['report_date'], name='suspicious__report__714f33_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousactivityreport',
            index=models.Index(fields=['report_status'], name='suspicious__report__57333b_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousactivityreport',
            index=models.Index(fields=['suspicious_activity_type'], name='suspicious__suspici_23f65c_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousactivityreport',
            index=models.Index(fields=['primary_subject_id'], name='suspicious__primary_6998f7_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousactivityreport',
            index=models.Index(fields=['primary_account_number'], name='suspicious__primary_c3229a_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousactivityreport',
            index=models.Index(fields=['risk_level'], name='suspicious__risk_le_a541cc_idx'),
        ),
    ]
