# Generated by Django 5.1.3 on 2025-04-10 12:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0021_suspiciousactivityreport_transactionmonitoringconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMLSettingsVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(max_length=100)),
                ('approval_date', models.DateTimeField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'AML Settings Version',
                'verbose_name_plural': 'AML Settings Versions',
            },
        ),
        migrations.DeleteModel(
            name='TransactionMonitoringConfig',
        ),
        migrations.RenameField(
            model_name='amlsettings',
            old_name='last_updated',
            new_name='modified_at',
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='amount_factor_weight',
            field=models.DecimalField(decimal_places=2, default=0.3, help_text='Weight factor for transaction amount in risk scoring (0-1)', max_digits=5),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='behavior_factor_weight',
            field=models.DecimalField(decimal_places=2, default=0.25, help_text='Weight factor for behavior patterns in risk scoring (0-1)', max_digits=5),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='created_by',
            field=models.CharField(default=-1212, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='frequency_factor_weight',
            field=models.DecimalField(decimal_places=2, default=0.25, help_text='Weight factor for transaction frequency in risk scoring (0-1)', max_digits=5),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='geographical_factor_weight',
            field=models.DecimalField(decimal_places=2, default=0.2, help_text='Weight factor for geographical risk in scoring (0-1)', max_digits=5),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='low_alert_action',
            field=models.CharField(choices=[('freeze', 'Immediate freeze and manual review'), ('block', 'Block transaction and notify compliance'), ('hold', 'Hold transaction and alert manager'), ('routine', 'Flag for routine review within 48 hours'), ('process', 'Process with notification to compliance')], default='process', help_text='Action for low risk alerts', max_length=7),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='medium_alert_action',
            field=models.CharField(choices=[('freeze', 'Immediate freeze and manual review'), ('block', 'Block transaction and notify compliance'), ('hold', 'Hold transaction and alert manager'), ('routine', 'Flag for routine review within 48 hours'), ('process', 'Process with notification to compliance')], default='routine', help_text='Action for medium risk alerts', max_length=7),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='modified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='risk_score_classification',
            field=models.CharField(choices=[('low', 'Low Risk: 0-30'), ('medium', 'Medium Risk: 31-70'), ('high', 'High Risk: 71-90'), ('critical', 'Critical Risk: 91-100')], default='medium', help_text='Risk score classification thresholds', max_length=10),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='unusual_channel_score_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Risk score multiplier for unusual transaction channels', max_digits=5),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='velocity_baseline_days',
            field=models.IntegerField(default=30, help_text='Days to establish baseline transaction velocity'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='velocity_threshold_multiplier',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Multiplier of normal velocity to trigger alert', max_digits=5),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='account_type',
            field=models.CharField(choices=[('individual_savings', 'Individual Savings'), ('individual_current', 'Individual Current'), ('business_small', 'Small Business'), ('business_medium', 'Medium Business'), ('business_large', 'Large Business'), ('trust', 'Trust Accounts'), ('wealth', 'Wealth Management'), ('government', 'Government'), ('non_profit', 'Non-Profit Organization')], default='individual_savings', max_length=20),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='cash_deposit_limit',
            field=models.DecimalField(decimal_places=4, default=5000, help_text='Cash deposit limit before enhanced monitoring', max_digits=19),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='cash_max_amount_per_tx',
            field=models.DecimalField(decimal_places=4, default=9999, help_text='Maximum amount per cash transaction to consider for structuring', max_digits=19),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='cash_min_transaction_count',
            field=models.IntegerField(default=3, help_text='Minimum number of cash transactions to consider for structuring'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='cash_time_window',
            field=models.IntegerField(default=48, help_text='Time window in hours to analyze for structuring'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='circular_transaction_window',
            field=models.IntegerField(default=72, help_text='Time window in hours to detect circular transactions'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='connection_failure_action',
            field=models.CharField(choices=[('stricter', 'Default to stricter thresholds'), ('hold', 'Hold all transactions'), ('flag', 'Process with manual review flag')], default='stricter', help_text='Action when external services are unavailable', max_length=10),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='critical_alert_action',
            field=models.CharField(choices=[('freeze', 'Immediate freeze and manual review'), ('block', 'Block transaction and notify compliance'), ('hold', 'Hold transaction and alert manager'), ('routine', 'Flag for routine review within 48 hours'), ('process', 'Process with notification to compliance')], default='freeze', help_text='Action for critical risk alerts', max_length=7),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='dormant_account_transfer_limit',
            field=models.DecimalField(decimal_places=4, default=5000, help_text='Threshold for transfers from dormant accounts', max_digits=19),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='electronic_min_frequency',
            field=models.IntegerField(default=3, help_text='Minimum frequency of round figure transactions to flag'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='electronic_round_figures',
            field=models.CharField(choices=[('1000', 'Multiples of $1,000'), ('500', 'Multiples of $500'), ('100', 'Multiples of $100')], default='1000', help_text='Round figure detection threshold', max_length=4),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='electronic_time_window',
            field=models.IntegerField(default=7, help_text='Time window in days for round figure analysis'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='geo_mismatch_hours',
            field=models.IntegerField(default=24, help_text='Time window in hours for geographical mismatch detection'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='geo_mismatch_locations',
            field=models.IntegerField(default=3, help_text='Number of different geographical locations that trigger alert'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='high_alert_action',
            field=models.CharField(choices=[('freeze', 'Immediate freeze and manual review'), ('block', 'Block transaction and notify compliance'), ('hold', 'Hold transaction and alert manager'), ('routine', 'Flag for routine review within 48 hours'), ('process', 'Process with notification to compliance')], default='hold', help_text='Action for high risk alerts', max_length=7),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='inactive_days_threshold',
            field=models.IntegerField(default=60, help_text='Days of inactivity to flag an account as dormant'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='max_processing_latency',
            field=models.IntegerField(default=3, help_text='Maximum processing latency in seconds'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='max_transaction_amount',
            field=models.DecimalField(decimal_places=4, default=10000, help_text='Maximum transaction amount before flagging', max_digits=19),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='rapid_withdrawal_threshold',
            field=models.DecimalField(decimal_places=2, default=90.0, help_text='Percentage threshold for rapid withdrawals after deposit', max_digits=5),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='rapid_withdrawal_window',
            field=models.IntegerField(default=24, help_text='Time window in hours for rapid withdrawal detection'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='structuring_detection_limit',
            field=models.DecimalField(decimal_places=4, default=3000, help_text='Threshold for detecting potential structuring', max_digits=19),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='transaction_queue_priority',
            field=models.CharField(choices=[('high_value', 'High-value transactions first'), ('chronological', 'Chronological order'), ('risk', 'Risk-based prioritization')], default='risk', help_text='How transactions are prioritized for processing', max_length=13),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='version',
            field=models.ForeignKey(default=-1212, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='aml_app.amlsettingsversion'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='amlsettings',
            unique_together={('version', 'account_type')},
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='cash_deposit_without_withdrawal',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='employee_risk_flag',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='high_cash_ratio_threshold',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='high_cash_ratio_window',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='high_priority_alerts',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='high_risk_countries',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='linked_account_threshold',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='low_priority_alerts',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='medium_priority_alerts',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='mismatched_behavior_multiplier',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='multiple_beneficiaries_count',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='multiple_beneficiaries_days',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='pep_enhanced_monitoring',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='standard_alert_action',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='transfer_time_window',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='watchlist_check_freq',
        ),
    ]
