# Generated by Django 5.1.3 on 2025-04-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0022_amlsettingsversion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amlsettings',
            old_name='rapid_withdrawal_window',
            new_name='rapid_withdrawal_window_hours',
        ),
        migrations.AlterUniqueTogether(
            name='amlsettings',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='amount_risk_weight',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Weight for transaction amount in risk score calculation', max_digits=5),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='cash_transaction_threshold',
            field=models.DecimalField(decimal_places=4, default=5000.0, help_text='Threshold for cash transaction reporting', max_digits=19),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='circular_transaction_hours',
            field=models.IntegerField(default=72, help_text='Time window in hours for circular transaction detection'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='country_risk_weight',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='Weight for country risk in risk score calculation', max_digits=5),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='critical_risk_action',
            field=models.CharField(choices=[('BLOCK', 'Block transaction'), ('HOLD', 'Hold for review'), ('FLAG', 'Flag but process'), ('MONITOR', 'Process with enhanced monitoring')], default='BLOCK', max_length=10),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='customer_risk_weight',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='Weight for customer risk in risk score calculation', max_digits=5),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='dormant_activation_days',
            field=models.IntegerField(default=90, help_text='Days of inactivity to consider account dormant'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='high_risk_action',
            field=models.CharField(choices=[('BLOCK', 'Block transaction'), ('HOLD', 'Hold for review'), ('FLAG', 'Flag but process'), ('MONITOR', 'Process with enhanced monitoring')], default='HOLD', max_length=10),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='high_risk_countries',
            field=models.TextField(default='AF,KP,IR,SY,VE,RU,BY,MM,CU', help_text='Comma-separated ISO country codes'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='large_transaction_threshold',
            field=models.DecimalField(decimal_places=4, default=10000.0, help_text='Threshold for large transaction reporting', max_digits=19),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='low_risk_action',
            field=models.CharField(choices=[('BLOCK', 'Block transaction'), ('HOLD', 'Hold for review'), ('FLAG', 'Flag but process'), ('MONITOR', 'Process with enhanced monitoring')], default='MONITOR', max_length=10),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='medium_risk_action',
            field=models.CharField(choices=[('BLOCK', 'Block transaction'), ('HOLD', 'Hold for review'), ('FLAG', 'Flag but process'), ('MONITOR', 'Process with enhanced monitoring')], default='FLAG', max_length=10),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='medium_risk_countries',
            field=models.TextField(default='AE,SA,NG,KE,PA,VN,KH', help_text='Comma-separated ISO country codes'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='pattern_risk_weight',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Weight for transaction pattern in risk score calculation', max_digits=5),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='pep_enhanced_due_diligence',
            field=models.BooleanField(default=True, help_text='Apply enhanced due diligence for PEPs'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='pep_transaction_threshold',
            field=models.DecimalField(decimal_places=4, default=1000.0, help_text='Lower threshold for PEP transaction monitoring', max_digits=19),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='rapid_withdrawal_percentage',
            field=models.DecimalField(decimal_places=2, default=90.0, help_text='Percentage of deposit withdrawn rapidly', max_digits=5),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='risk_level_critical',
            field=models.IntegerField(default=90, help_text='Minimum score for Critical risk classification'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='risk_level_high',
            field=models.IntegerField(default=75, help_text='Minimum score for High risk classification'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='risk_level_medium',
            field=models.IntegerField(default=50, help_text='Minimum score for Medium risk classification'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='sanctions_screening_frequency',
            field=models.CharField(choices=[('REALTIME', 'Real-time'), ('HOURLY', 'Hourly batch'), ('DAILY', 'Daily batch')], default='REALTIME', max_length=10),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='structuring_detection_threshold',
            field=models.DecimalField(decimal_places=4, default=3000.0, help_text='Threshold for potential structuring activity', max_digits=19),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='structuring_time_window_hours',
            field=models.IntegerField(default=48, help_text='Time window in hours for structuring detection'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='structuring_transaction_count',
            field=models.IntegerField(default=3, help_text='Minimum number of transactions to trigger structuring alert'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='velocity_amount_threshold',
            field=models.DecimalField(decimal_places=4, default=15000.0, help_text='Total amount threshold for velocity checks', max_digits=19),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='velocity_count_threshold',
            field=models.IntegerField(default=5, help_text='Number of transactions threshold for velocity'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='velocity_time_window_hours',
            field=models.IntegerField(default=24, help_text='Time window in hours for velocity checks'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='watchlist_screening_frequency',
            field=models.CharField(choices=[('REALTIME', 'Real-time'), ('HOURLY', 'Hourly batch'), ('DAILY', 'Daily batch')], default='REALTIME', max_length=10),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='account_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual Account'), ('BUSINESS', 'Business Account'), ('TRUST', 'Trust Account'), ('WEALTH', 'Wealth Management'), ('NONPROFIT', 'Non-Profit Organization')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='created_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='modified_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='amount_factor_weight',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='behavior_factor_weight',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='cash_deposit_limit',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='cash_max_amount_per_tx',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='cash_min_transaction_count',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='cash_time_window',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='circular_transaction_window',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='connection_failure_action',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='critical_alert_action',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='dormant_account_transfer_limit',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='electronic_min_frequency',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='electronic_round_figures',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='electronic_time_window',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='frequency_factor_weight',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='geo_mismatch_hours',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='geo_mismatch_locations',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='geographical_factor_weight',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='high_alert_action',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='inactive_days_threshold',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='low_alert_action',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='max_processing_latency',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='max_transaction_amount',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='medium_alert_action',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='rapid_withdrawal_threshold',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='risk_score_classification',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='structuring_detection_limit',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='transaction_queue_priority',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='unusual_channel_score_multiplier',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='velocity_baseline_days',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='velocity_threshold_multiplier',
        ),
        migrations.RemoveField(
            model_name='amlsettings',
            name='version',
        ),
    ]
