# Generated by Django 5.1.3 on 2025-04-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0023_rename_rapid_withdrawal_window_amlsettings_rapid_withdrawal_window_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amlsettings',
            name='cash_deposit_limit',
            field=models.FloatField(default=5000.0),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='circular_transaction_window',
            field=models.IntegerField(default=72),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='critical_alert_action',
            field=models.CharField(default='freeze', max_length=20),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='dormant_account_activity',
            field=models.BooleanField(default=True, help_text='Flag dormant accounts suddenly receiving large deposits'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='frequent_currency_exchange',
            field=models.BooleanField(default=True, help_text='Flag frequent exchange of cash into other currencies'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='geo_mismatch_hours',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='geo_mismatch_locations',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='high_alert_action',
            field=models.CharField(default='hold', max_length=20),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='high_risk_jurisdictions',
            field=models.BooleanField(default=True, help_text='Flag transfers to/from high-risk jurisdictions'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='high_risk_jurisdictions_customers',
            field=models.BooleanField(default=True, help_text='Flag customers linked to high-risk jurisdictions'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='inactive_days_threshold',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='inconsistent_transactions',
            field=models.BooleanField(default=True, help_text="Flag transactions inconsistent with customer's known business activities"),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='large_cash_deposits',
            field=models.BooleanField(default=True, help_text='Flag unusually large cash deposits inconsistent with customer profile'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='max_transaction_amount',
            field=models.FloatField(default=10000.0),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='mismatched_behavior_multiplier',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='nonprofit_suspicious',
            field=models.BooleanField(default=True, help_text='Flag non-profit organizations with unexplained transactions'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='rapid_fund_movement',
            field=models.BooleanField(default=True, help_text='Flag rapid movement of funds in and out of accounts'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='shell_companies',
            field=models.BooleanField(default=True, help_text='Flag trusts or shell companies with no clear business purpose'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='small_frequent_transfers',
            field=models.BooleanField(default=True, help_text='Flag frequent small transfers that may indicate avoidance of detection'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='standard_alert_action',
            field=models.CharField(default='routine', max_length=20),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='structured_deposits',
            field=models.BooleanField(default=True, help_text='Flag structuring deposits to avoid reporting thresholds'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='structuring_detection_limit',
            field=models.FloatField(default=3000.0),
        ),
    ]
