# Generated by Django 5.1.3 on 2025-04-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0024_amlsettings_cash_deposit_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amlsettings',
            name='currency_exchange_count_threshold',
            field=models.IntegerField(default=3, help_text='Number of currency exchanges within time window to trigger flag'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='currency_exchange_time_window',
            field=models.IntegerField(default=7, help_text='Time window in days for currency exchange frequency'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='dormant_activity_amount',
            field=models.DecimalField(decimal_places=4, default=3000.0, help_text='Amount threshold for flagging activity on dormant accounts', max_digits=19),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='dormant_days_threshold',
            field=models.IntegerField(default=90, help_text='Days of inactivity to consider an account dormant'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='inconsistent_amount_multiplier',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Multiplier of average transaction size to trigger inconsistency flag', max_digits=5),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='large_cash_deposits_threshold',
            field=models.DecimalField(decimal_places=4, default=5000.0, help_text='Amount threshold for flagging large cash deposits', max_digits=19),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='nonprofit_transaction_threshold',
            field=models.DecimalField(decimal_places=4, default=5000.0, help_text='Amount threshold for flagging non-profit transactions', max_digits=19),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='rapid_movement_percentage',
            field=models.DecimalField(decimal_places=2, default=75.0, help_text='Percentage of funds moved quickly to trigger flag', max_digits=5),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='rapid_movement_window',
            field=models.IntegerField(default=24, help_text='Time window in hours for rapid movement detection'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='shell_company_age_threshold',
            field=models.IntegerField(default=365, help_text='Age threshold in days for new shell company monitoring'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='small_transfer_frequency',
            field=models.IntegerField(default=5, help_text='Number of small transfers within window to trigger flag'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='small_transfer_threshold',
            field=models.DecimalField(decimal_places=4, default=1000.0, help_text="Amount threshold for what constitutes a 'small' transfer", max_digits=19),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='small_transfer_window',
            field=models.IntegerField(default=7, help_text='Time window in days for small transfer frequency'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='structured_deposits_count',
            field=models.IntegerField(default=3, help_text='Minimum number of deposits that could indicate structuring'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='structured_deposits_threshold',
            field=models.DecimalField(decimal_places=4, default=9000.0, help_text='Total amount of structured deposits to trigger flag', max_digits=19),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='structured_deposits_window',
            field=models.IntegerField(default=2, help_text='Time window in days to check for structuring'),
        ),
        migrations.AlterField(
            model_name='amlsettings',
            name='high_risk_countries',
            field=models.TextField(default='AF,KP,IR,SY,VE,RU,BY,MM,CU', help_text='Comma-separated ISO country codes of high-risk jurisdictions'),
        ),
    ]
