# Generated by Django 5.1.3 on 2025-04-15 08:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0025_amlsettings_currency_exchange_count_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
