# Generated by Django 5.1.3 on 2025-04-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0027_alter_customer_created_at_alter_customer_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
