# Generated by Django 5.1.3 on 2025-04-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0028_alter_customer_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction1',
            name='customer_id',
            field=models.CharField(default=-1212, max_length=20),
            preserve_default=False,
        ),
    ]
