# Generated by Django 5.1.3 on 2025-04-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0029_transaction1_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_type',
            field=models.CharField(default='INDIVIDUAL', max_length=20),
        ),
    ]
