# Generated by Django 5.1.3 on 2025-04-15 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0030_customer_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousTransaction1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('flagged_reason', models.TextField()),
                ('manual_review_required', models.BooleanField(default=True)),
                ('review_status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('id_document_type', models.CharField(blank=True, choices=[('Passport', 'Passport'), ('National ID', 'National ID'), ('Driver License', 'Driver License'), ('Other', 'Other')], max_length=50, null=True)),
                ('id_document_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account_type', models.CharField(blank=True, choices=[('Savings', 'Savings'), ('Current', 'Current'), ('Business', 'Business'), ('Other', 'Other')], max_length=50, null=True)),
                ('account_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Blacklisted', 'Blacklisted')], max_length=50, null=True)),
                ('sender_account', models.CharField(max_length=50)),
                ('receiver_account', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aml_app.transaction1')),
            ],
        ),
    ]
