# Generated by Django 5.1.3 on 2025-04-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0031_suspicioustransaction1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspicioustransaction1',
            name='receiver_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='suspicioustransaction1',
            name='sender_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
