# Generated by Django 5.1.3 on 2025-04-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0032_alter_suspicioustransaction1_receiver_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='branch_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
