# Generated by Django 5.1.3 on 2025-04-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0034_transaction1_branch_code_transaction1_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='amlsettings',
            name='large_payments',
            field=models.BooleanField(default=True, help_text='Flag unusually large payments inconsistent with customer profile'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='large_payments_threshold',
            field=models.DecimalField(decimal_places=4, default=10000.0, help_text='Amount threshold for flagging large payments', max_digits=19),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='large_transfers',
            field=models.BooleanField(default=True, help_text='Flag unusually large transfers inconsistent with customer profile'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='large_transfers_threshold',
            field=models.DecimalField(decimal_places=4, default=7500.0, help_text='Amount threshold for flagging large transfers', max_digits=19),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='large_withdrawals',
            field=models.BooleanField(default=True, help_text='Flag unusually large withdrawals inconsistent with customer profile'),
        ),
        migrations.AddField(
            model_name='amlsettings',
            name='large_withdrawals_threshold',
            field=models.DecimalField(decimal_places=4, default=5000.0, help_text='Amount threshold for flagging large withdrawals', max_digits=19),
        ),
       
    ]
