# Generated by Django 5.1.3 on 2025-04-16 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0035_amlsettings_large_payments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='action_description',
            field=models.TextField(blank=True, help_text='Description of action taken as a result of the transaction', null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='behalf_entity',
            field=models.JSONField(blank=True, help_text='JSON object containing information about entity/person on whose behalf the transaction was conducted', null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='company',
            field=models.JSONField(blank=True, help_text='JSON object containing company details (name, registration_number, directors, directors_contact, directors_address, company_account, directors_accounts, business_type, address)', null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='individual',
            field=models.JSONField(blank=True, help_text='JSON object containing individual details (surname, full_name, nationality, account_numbers, identity_number)', null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='reporting_entity',
            field=models.CharField(blank=True, help_text="Reporting entity's branch or division", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='reporting_person',
            field=models.CharField(blank=True, help_text='Reporting person and contact details', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='transaction_comment',
            field=models.TextField(blank=True, help_text='Comment about transaction types', null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='transaction_types',
            field=models.JSONField(blank=True, help_text='JSON array of transaction types involved', null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='action_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='beneficiary_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='beneficiary_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='beneficiary_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='customer_nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='customer_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='entity_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='entity_business_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='entity_directors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='entity_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='entity_registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='is_entity',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='law_enforcement_contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='law_enforcement_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='transaction_method',
            field=models.CharField(blank=True, choices=[('bank_cash', 'Bank Cash'), ('bank_cheques', 'Bank Cheques'), ('electronic_funds_transfer', 'Electronic Funds Transfer'), ('money_transfer', 'Money Transfer Business'), ('foreign_exchange', 'Foreign Exchange'), ('travelers_cheques', "Traveler's Cheques"), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='transaction_method_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default='12-12-1212'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SuspiciousTransactionReport',
            fields=[
                ('report_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('reporting_date', models.DateField()),
                ('reporting_entity', models.CharField(max_length=255)),
                ('reporting_person', models.TextField()),
                ('branch_code', models.CharField(blank=True, max_length=20, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True)),
                ('flagged_reason', models.TextField(blank=True, null=True)),
                ('manual_review_required', models.BooleanField(default=True)),
                ('review_status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('individual_surname', models.CharField(blank=True, max_length=255, null=True)),
                ('individual_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('individual_nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('individual_account_numbers', models.TextField(blank=True, null=True)),
                ('individual_identity_number', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('id_document_type', models.CharField(blank=True, choices=[('Passport', 'Passport'), ('National ID', 'National ID'), ('Driver License', 'Driver License'), ('Other', 'Other')], max_length=50, null=True)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('customer_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account_type', models.CharField(blank=True, choices=[('Savings', 'Savings'), ('Current', 'Current'), ('Business', 'Business'), ('Other', 'Other')], max_length=50, null=True)),
                ('account_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Blacklisted', 'Blacklisted')], max_length=50, null=True)),
                ('is_entity', models.BooleanField(blank=True, default=False, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('company_directors', models.TextField(blank=True, null=True)),
                ('company_directors_contact', models.TextField(blank=True, null=True)),
                ('company_directors_address', models.TextField(blank=True, null=True)),
                ('company_account', models.CharField(blank=True, max_length=100, null=True)),
                ('company_directors_accounts', models.TextField(blank=True, null=True)),
                ('company_business_type', models.CharField(blank=True, max_length=255, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('suspicious_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sender_account', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver_account', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_types', models.JSONField(default=list)),
                ('transaction_comment', models.TextField(blank=True, null=True)),
                ('behalf_entity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('behalf_entity_directors', models.TextField(blank=True, null=True)),
                ('behalf_entity_business_type', models.CharField(blank=True, max_length=255, null=True)),
                ('behalf_entity_account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('behalf_entity_address', models.TextField(blank=True, null=True)),
                ('beneficiary_name', models.CharField(blank=True, max_length=200, null=True)),
                ('beneficiary_account', models.CharField(blank=True, max_length=50, null=True)),
                ('beneficiary_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('beneficiary_address', models.TextField(blank=True, null=True)),
                ('suspicious_description', models.TextField()),
                ('action_description', models.TextField(blank=True, null=True)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('law_enforcement_contacted', models.BooleanField(default=False)),
                ('law_enforcement_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aml_app.transaction1')),
            ],
            options={
                'verbose_name': 'Suspicious Transaction ',
            },
        ),
    ]
