# Generated by Django 5.1.3 on 2025-04-16 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0036_suspiciousactivityreport_action_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suspicioustransaction1',
            old_name='entity_address',
            new_name='action_description',
        ),
        migrations.RenameField(
            model_name='suspicioustransaction1',
            old_name='customer_name',
            new_name='behalf_entity_account_number',
        ),
        migrations.RenameField(
            model_name='suspicioustransaction1',
            old_name='entity_directors',
            new_name='behalf_entity_address',
        ),
        migrations.RenameField(
            model_name='suspicioustransaction1',
            old_name='transaction_method_comment',
            new_name='behalf_entity_directors',
        ),
        migrations.RenameField(
            model_name='suspicioustransaction1',
            old_name='customer_nationality',
            new_name='company_account',
        ),
        migrations.RenameField(
            model_name='suspicioustransaction1',
            old_name='entity_business_type',
            new_name='company_registration_number',
        ),
        migrations.RenameField(
            model_name='suspicioustransaction1',
            old_name='entity_registration_number',
            new_name='individual_identity_number',
        ),
        migrations.RemoveField(
            model_name='suspicioustransaction1',
            name='entity_name',
        ),
        migrations.RemoveField(
            model_name='suspicioustransaction1',
            name='id',
        ),
        migrations.RemoveField(
            model_name='suspicioustransaction1',
            name='id_document_number',
        ),
        migrations.RemoveField(
            model_name='suspicioustransaction1',
            name='transaction_method',
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='behalf_entity_business_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='behalf_entity_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='company_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='company_business_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='company_directors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='company_directors_accounts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='company_directors_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='company_directors_contact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='individual_account_numbers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='individual_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='individual_nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='individual_surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='report_id',
            field=models.CharField(default= "1212-12-12", max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='reporting_date',
            field=models.DateField(default='1212-12-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='reporting_entity',
            field=models.CharField(default= "1212-12-12", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='reporting_person',
            field=models.TextField(default= "1212-12-12"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='suspicious_date',
            field=models.DateField(default= "1212-12-12"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='suspicious_description',
            field=models.TextField(default= "1212-12-12"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='transaction_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspicioustransaction1',
            name='transaction_types',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='suspicioustransaction1',
            name='flagged_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suspicioustransaction1',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='suspicioustransaction1',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aml_app.transaction1'),
        ),
    ]
