# Generated by Django 5.1.3 on 2025-04-17 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_app', '0037_rename_entity_address_suspicioustransaction1_action_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='account_status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Blacklisted', 'Blacklisted')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Savings', 'Savings'), ('Current', 'Current'), ('Business', 'Business'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='action_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='999.0', max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='behalf_entity_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='behalf_entity_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='behalf_entity_business_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='behalf_entity_directors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='behalf_entity_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='beneficiary_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='beneficiary_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='beneficiary_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='branch_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='company_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='company_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='company_business_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='company_directors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='company_directors_accounts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='company_directors_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='company_directors_contact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='company_registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='customer_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='flagged_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='id_document_type',
            field=models.CharField(blank=True, choices=[('Passport', 'Passport'), ('National ID', 'National ID'), ('Driver License', 'Driver License'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='individual_account_numbers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='individual_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='individual_identity_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='individual_nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='individual_surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='is_entity',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='law_enforcement_contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='law_enforcement_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='manual_review_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='receiver_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='reporting_date',
            field=models.DateField(default='1212-12-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='resolved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='review_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='sender_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='suspicious_date',
            field=models.DateField(default='1212-12-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aml_app.transaction1'),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
